- name: Check for voice best practices on a Meraki voice network
  connection: local
  hosts: localhost
  gather_facts: False
  pre_tasks:
    - include_vars:
        file: vars.yml
        name: env
    - name: Get organization ID
      meraki_organization:
        auth_key: '{{env.api_key}}'
        org_name: '{{env.org_name}}'
        state: query
      register: org_info
    - name: Get network ID
      meraki_network:
        auth_key: '{{env.api_key}}'
        org_id: '{{org_info.data.id}}'
        net_name: '{{env.net_name}}'
        state: query
      register: net_info
    - set_fact:
        org_id: '{{org_info.data.id}}'
        net_id: '{{net_info.data.id}}'
        # recommendations: "Recommendations:"
        recommendations:
          -
  tasks:
    - name: Check SSID settings
      meraki_ssid:
        auth_key: '{{env.api_key}}'
        org_id: '{{org_id}}'
        net_id: '{{net_id}}'
        name: '{{env.ssid_name}}'
        state: query
      register: ssid_info
    - debug:
        var: ssid_info
    - name: Add recommendation for authentication type
      set_fact:
        recommendations: '{{recommendations}} + {{new_msg}}'
      when: ssid_info.data.authMode !=  "psk" or ssid_info.data.encryptionMode != "wp"
      vars:
        new_msg:
          - "- Set authentication type to pre-shared key with WPA2"
    - name: Add recommendation for authentication type
      set_fact:
        recommendations: '{{recommendations}} + {{new_msg}}'
      when: ssid_info.data.wpaEncryptionMode != "WPA2 onl"
      vars:
        new_msg:
          - "- Set WPA encryption mode to WPA2 only"
    - name: Add recommendation for band selection
      set_fact:
        recommendations: '{{recommendations}} + {{new_msg}}'
      when: ssid_info.data.bandSelection != "5 GHz band only"
      vars:
        new_msg:
          - "- Set band selection to 5 GHz only"
    - name: Add recommendation for band selection
      set_fact:
        recommendations: '{{recommendations}} + {{new_msg}}'
      when: ssid_info.data.minBitrate < 12
      vars:
        new_msg:
          - "- Set minimum bitrate to 12 Mbps or higher"
    - name: Add recommendation for IP assignment mode
      set_fact:
        recommendations: '{{recommendations}} + {{new_msg}}'
      when: ssid_info.data.ipAssignmentMode != "Bridge mod"  
      vars:
        new_msg:
          - "- Set IP address assignment mode to Bridge Mode"
    - debug:
        var: recommendations
